# shells and standard command line utilities
brew 'zsh'
brew 'fish'
brew 'bash'
brew 'coreutils'
brew 'parallel'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'readline'
brew 'tree'
brew 'htop'
brew 'p7zip'
brew 'lbzip2'
brew 'unar'
brew 'gnupg'
brew 'xz'

# meta environments for my regularly used programming languages
brew 'asdf' # handles python, nodejs, and ruby
# brew 'rustup-init' # installed in provision-mac.sh

# other programming languages
## ones I actually use
brew 'go'
brew 'r'

## hoping these become a thing
brew 'deno'
brew 'zig'

## don't really use, but needed for other things
brew 'openjdk'

## ones I keep meaning to learn
brew 'erlang'
brew 'elixir'
brew 'elm'
brew 'mit-scheme'
brew 'ghc'
brew 'cabal-install'
brew 'haskell-stack'
brew 'haxe'

# network stuff
brew 'wget'
brew 'nmap'
brew 'tor'
brew 'croc'
brew 'elinks'

# dev tools
brew 'neovim'

brew 'git'
brew 'git-lfs'
brew 'hub'
brew 'gh'
brew 'bfg'
brew 'mercurial'
brew 'svn'

brew 'cmake'
brew 'scons'
brew 'automake'
brew 'clang-format'
brew 'swig'
brew 'ctags'
brew 'qcachegrind'

brew 'libyaml'
brew 'flatbuffers'

brew 'qemu'
brew 'podman'
brew 'doctl'

brew 'ripgrep'
brew 'jq'
brew 'sqlite'

# graphics tools
brew 'imagemagick'
brew 'ghostscript'
brew 'pdf2svg'
brew 'svg2png'
brew 'woff2'
brew 'pngcrush'
brew 'pngquant'
brew 'zopfli'
brew 'guetzli'
brew 'mozjpeg'
brew 'gifski'

# various and sundry
brew 'hugo'
brew 'zola'
brew 'pandoc'
brew 'pandoc-citeproc'
brew 'multimarkdown'
brew 'lame'
brew 'libdvdcss'
brew 'youtube-dl'
brew 'ffmpeg'
brew 'libav'
brew 'speedtest-cli'
brew 'dieharder'
brew 'dockutil'
brew 'defaultbrowser'
brew 'duti'
brew 'trash'
brew 'terminal-notifier'

# amusements!
brew 'nethack'
brew 'frotz'
brew 'solarus'


# now getting into full macOS apps
tap 'homebrew/cask'
tap 'homebrew/cask-versions'

# infrastructure
cask '1password'
# cask 'backblaze' # don't use homebrew for this; upgrade will bork things
cask 'little-snitch'
cask 'mullvadvpn'

# internet
cask 'firefox'
cask 'google-chrome'
cask 'tor-browser'
cask 'transmit'
cask 'transmission'
cask 'whatsapp'
cask 'telegram'
cask 'skype'
cask 'slack'
cask 'zoom'
cask 'webex'
cask 'microsoft-teams'
cask 'discord'
cask 'signal'

# writing and office
cask 'scrivener'
cask 'microsoft-office'
cask 'zotero'
cask 'zettlr'
cask 'basictex'
cask 'anki'
cask 'skim'

# development
cask 'sublime-text'
cask 'visual-studio-code'
cask 'visual-studio'
cask 'dash'
cask 'macdown'
cask 'processing'
cask 'kaleidoscope'
cask 'sourcetree'
cask 'hexfiend'
cask 'insomnia'
cask 'robo-3t'
cask 'postgres'
cask 'github'
cask 'zerobranestudio'
cask 'sf-symbols'

# programming languages
cask 'dotnet-sdk'
cask 'mono-mdk'
cask 'rstudio'
cask 'julia'

# artsy/media
cask 'unity-hub'
# cask 'godot' # manually install godot to control versioning
# cask 'godot-mono'
cask 'blender'
cask 'dust3d'
cask 'inkscape'
cask 'texturepacker'
cask 'bfxr'
cask 'twine'
cask 'inky'
cask 'nodebox'
cask 'obs'

# various virtualization thingies
cask 'vmware-fusion'
cask 'virtualbox'
cask 'docker'

# entertainment
cask 'itch'
cask 'gog-galaxy'
cask 'epic-games'
cask 'steam'
cask 'nvidia-geforce-now'
cask 'dwarf-fortress'
cask 'minecraft'
cask 'handbrake'
cask 'vlc'
cask 'iina'
cask 'mpv'
cask 'amazon-music'
cask 'calibre'
cask 'kindle'
cask 'kindle-previewer'
cask 'yacreader'
cask 'cloudlibrary'
cask 'adobe-digital-editions'

# utilities
cask 'hammerspoon'
cask 'arq'
cask 'the-unarchiver'
cask 'selfcontrol'
cask 'time-out'
cask 'balenaetcher'
cask 'unetbootin'
cask 'mkvtoolnix'
cask 'keepingyouawake'
cask 'a-better-finder-rename'
cask 'pastebot'
cask 'crunch'

# quicklook stuff
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'suspicious-package'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'apparency'


# a few monospaced fonts from caskroom
#   (others handled outside of script)
tap  'homebrew/cask-fonts'
cask 'font-fira-code'
cask 'font-juliamono'


# my own apps
tap  'sjml/sjml'
cask 'dotfile-watcher'
cask 'dualcam'


# and finally, stuff from the Mac App Store
brew 'mas'

# development
mas 'Xcode',               id: 497799835
mas 'Base',                id: 402383384
mas 'Calca',               id: 635758264
mas 'Ultra Character Map', id: 520265986

# internet
# mas 'Tweetbot',            id: 557168941 # (kinda just use the website now, if at all)
mas 'Messenger',           id: 1480068668

# media
# mas 'GarageBand',          id: 682658836 # (takes up too much space)
mas 'iMovie',              id: 408981434

# utility
mas 'GrandPerspective',    id: 1111570163
mas 'Menu World Time',     id: 1446377255

# graphics and office
mas 'Pixelmator Pro',      id: 1289583905
mas 'Affinity Designer',   id: 824171161
mas 'GIF Brewery 3',       id: 1081413713
mas 'GIPHY Capture',       id: 668208984
mas 'Pages',               id: 409201541
mas 'Numbers',             id: 409203825
mas 'Keynote',             id: 409183694
mas 'Highland 2',          id: 1171820258
