#!/usr/bin/env bash

##########
### Doesn't work anymore; BC seems to have borked something on their
###   Cisco setup so you can't access it with openconnect any more. >:(
### Leaving here for now as a reference.
##########


# Boston College requires an AnyConnect VPN to access certain services.
#   I don't like extra VPN software running, so I use the OpenConnect
#   command line program instead.
# This scripts the access, snagging my password from the 1Password CLI
#   and requesting a 2FA prompt from Duo. So all I need to do is run
#   this script, authenticate with my TouchID, and I'm good to go!
# (NB to use TouchID with sudo:
#   https://web.archive.org/web/20210905125725/https://sixcolors.com/post/2020/11/quick-tip-enable-touch-id-for-sudo/ )

sudocheck=$(sudo -nv 2>&1)
if [ $? -ne 0 ]; then
    echo "Need sudo password:"
    sudo -v
fi

mullvad_connected=0
MULLVAD=$(which mullvad)
if [[ ${#MULLVAD} -ne 0 ]]; then
    mullvad_status=$($MULLVAD status)
    if [[ $mullvad_status == Connected* ]]; then
        mullvad_connected=1
    fi
fi

if [[ $mullvad_connected -eq 1 ]]; then
    echo "Temporarily disconnecting from Mullvad VPN..."
    mullvad disconnect
    echo "Waiting for Mullvad disconnection to settle..."
    sleep 5
fi

set -e

echo "Getting BC password from 1Password..."
eval $(op signin)
bcpw=$(op item get "Boston College" --format=json | jq --raw-output '.fields[] | select(.id=="password").value')

echo "Starting up VPN..."
sudo expect -c "
    spawn sudo openconnect eaglevpn.bc.edu --config=$HOME/.config/bcvpn.conf
    expect \"Password:\"
    send \"$bcpw\n\"
    expect \"Response:\"
    send \"1\n\"
    interact
"

if [[ $mullvad_connected -eq 1 ]]; then
    echo "Waiting for OpenConnect disconnection to settle..."
    sleep 5
    echo "Reconnecting to Mullvad VPN..."
    mullvad connect
fi
