#!/usr/bin/env zsh


if [[ $(uname -m) == 'arm64' ]]; then
  _brew="/opt/homebrew/bin/brew"
else
  _brew="/usr/local/bin/brew"
fi

# I grew weary of homebrew's pedantry
if [[ "$1" == "cask" ]]; then
    $_brew $2 --cask $@[3,-1]
else
    $_brew $@
fi
