#!/usr/bin/env bash

#####
#####
#  Realizing I haven't run this in months, so maybe the
#    bug was fixed? Keeping around just in case I need
#    it again someday.
#####
#####

# The mullvad daemon has a lot of trouble waking from sleep.
# It's either this or restart the computer.
# (This only started happening about a year ago; Mullvad
#    support is mystified and not super helpful, which is a bummer.)

# need sudo to do the killing
sudo -v

# first kill the GUI app
killall "Mullvad VPN"
sleep 1 # give it a bit

# now the daemon (will automatically restart)
sudo pkill -9 mullvad-daemon
sleep 1 # give it a bit

# restart the GUI
open -a "Mullvad VPN"
