#!/usr/bin/env bash

if [[ $(uname -m) == 'arm64' ]]; then
  SUBL="/opt/homebrew/bin/subl"
else
  SUBL="/usr/local/bin/subl"
fi

if [[ -x $SUBL ]]; then
    $SUBL -w $*
else
    # fallback for if ST doesn't actually exist
    $EDITOR $*
fi

