#!/bin/zsh

make-ssh-key() {
    # Creating local keys (that will have to be manually uploaded to their
    #   respective hosts.

    if [[ -n $1 ]]; then
      keyname=$1
    else
      echo -n "Enter name for new key: "
      read keyname
    fi

    email="shane@techie.net"
    byteSize=4096
    keyPath=$HOME/.ssh

    privateKey=$keyPath/${keyname}_rsa
    if [[ -a $privateKey ]]; then
      echo "$keyname already exists. Skipping."
      continue
    fi

    finished=0
    echo "GENERATING SSH KEY FOR $keyname"
    while [[ $finished -eq 0 ]]; do
      echo -n "  Passphrase: "
      read -s pass1
      echo
      echo -n "  Confirm passphrase: "
      read -s pass2
      echo
      if [[ $pass1 != $pass2 ]]; then
          echo "Passphrases don't match. Try again!" >&2
          continue
      fi
      if [[ ${#pass1} -lt 5 ]]; then
          echo "Passphrase is too short. Try again!" >&2
          continue
      fi
      finished=1
    done

    ssh-keygen -t rsa -b $byteSize -C $email -N $pass1 -f $privateKey
    echo
}
