#!/usr/bin/env zsh

# Only run pip normally if we're currently running it from
#  a virtual environment. Otherwise only let it install to
#  the local user directory.

pip2() {
  if [[ -n $VIRTUAL_ENV ]]; then
    $VIRTUAL_ENV/bin/pip "$@"
  else
    _pip="$(/usr/bin/env python2 -m site --user-base)/bin/pip"
    PIP_USER=1 $_pip "$@"
  fi
}
