#!/bin/zsh

# TODO: add some color to this
tmuxInfo() {
  local numSess=$(tmux ls 2>/dev/null | wc -l | tr -d "[:blank:]")
  if [[ $numSess = '0' ]] then
    # echo "No active tmux sessions."
  elif [[ $numSess = '1' ]] then
    echo "There is one active tmux session."
  else
    echo "There are $numSess active tmux sessions."
  fi
}

